[program:rus_tili_tarjimon_bot]
directory=/root/translators/rus_tili_tarjimon_bot
command=/root/translators/rus_tili_tarjimon_bot/venv/bin/python3 app.py
; Replace '/path/to/your/venv' with the actual path to your virtual environment

autostart=true
autorestart=true
environment=HOME="/root/translators/rus_tili_tarjimon_bot"
user=root
stderr_logfile=/root/translators/rus_tili_tarjimon_bot/log.err.log
stdout_logfile=/root/translators/rus_tili_tarjimon_bot/log.out.log


